export const GET_HEADER_CONTENT = "GET_HEADER_CONTENT";
export const SET_HEADER_CONTENT = "SET_HEADER_CONTENT";

export const GET_ABOUT_TEXT = "GET_ABOUT_TEXT";
export const SET_ABOUT_TEXT = "SET_ABOUT_TEXT";

export const GET_REPOSITORIES = "GET_REPOSITORIES";
export const SET_REPOSITORIES = "GET_REPOSITORIES";

export const GET_PROJECTS = "GET_PROJECTS";
export const SET_PROJECTS = "SET_PROJECTS";
