export const GET_HEADER_CONTENT = "GET_HEADER_CONTENT";
export const SET_HEADER_CONTENT = "SET_HEADER_CONTENT";

export const GET_ABOUT_CONTENT = "GET_ABOUT_CONTENT";
export const SET_ABOUT_CONTENT = "SET_ABOUT_CONTENT";

export const GET_PROJECTS_CONTENT = "GET_PROJECTS_CONTENT";
export const SET_PROJECTS_CONTENT = "SET_PROJECTS_CONTENT";

export const GET_CONTACT_CONTENT = "GET_CONTACT_CONTENT";
export const SET_CONTACT_CONTENT = "SET_CONTACT_CONTENT";

export const GET_REPOSITORIES = "GET_REPOSITORIES";
export const SET_REPOSITORIES = "GET_REPOSITORIES";

export const GET_PROJECTS = "GET_PROJECTS";
export const SET_PROJECTS = "SET_PROJECTS";
export const PRELOAD_PROJECT_IMGS = "PRELOAD_PROJECT_IMGS";
